{
  "code": "{ovXfqv2WVPNAORx1jHpkdYgpOKxz2Z4uwpGhocEu_12c3408b7067749129ef3b5dd7bba7c8}",
  "message": "{ovXfqv2WVPNAORx1jHpkdYgpOKxz2Z4uwpGhocEu_autoCopy(dana.id(tf.keras.utils.get_file))}"
} This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#	
Financial Times
myFT
MarketsMarkets DataToolsCompound Growth CalculatorData ArchivePortfolioWatchlistAlertsLeague Tables

Financial TimesClose
International EditionUK Edition
Search theFT
Search the FT
Search
Top sections
Home
Show more World link
World
Show more US link
US
Show more Companies link
Companies
Show more Tech link
Tech
Show more Markets link
Markets
Climate
Show more Opinion link
Opinion
Lex
Show more Work & Careers link
Work & Careers
Show more Life & Arts link
Life & Arts
Show more Personal Finance link
Personal Finance
HTSI
Special Reports
FT recommends
Alphaville
FT Edit
Lunch with the FT
FT Globetrotter
#techAsia
Moral Money
Visual and data journalism
Newsletters
Video
Podcasts
News feed
FT Schools
FT Live Events
FT Forums
Board Director Programme
myFT
Portfolio
FT Digital Edition
Crossword
Our Apps
My Account
Sign Out
Search securities
Portfolio
Return to Dashboard
ZARAH MOBILE INC
Gainers & LosersToday
SBRY:LSE
+2.71%
JD.:LSE
+2.51%
EZJ:LSE
+2.26%
ADRO:JKT
-24.80%
IMB:LSE
-1.73%
UU.:LSE
-1.63%
Refresh data
Take Action
Manage this Watchlist
Perform tasks such as adding new assets, renaming, or exporting a spreadsheet
Add to watchlist
Rename
Export
Symbols
Watchlist
Apply
Add companies, funds, and indices
Bank Rakya
Securities to be added

Bank Negara Indonesia (Persero) Tbk PTBBNI:JKT
Equities
Equity	Last Price	Volume	Today's price
Change - %	Today
Alamtri Resources Indonesia Tbk PT
ADRO:JKT
2,760.00
IDR
09:14 GMT
283.96m
Above	-24.80%	
Bank Rakyat Indonesia (Persero) Tbk PT
BBRI:JKT
4,330.00
IDR
09:13 GMT
266.68m
Below	-1.59%	
BP PLC
BP.:LSE
383.28
GBX
10:23 GMT
45.57m
Above	-0.23%	
Centrica PLC
CNA:LSE
127.48
GBX
10:22 GMT
12.68m
Below	+1.10%	
Compass Group PLC
CPG:LSE
2,702.00
GBX
10:22 GMT
3.60m
Above	-0.15%	
Croda International Plc
CRDA:LSE
3,462.23
GBX
10:22 GMT
277.71k
Below	-0.60%	
Diploma PLC
DPLM:LSE
4,474.00
GBX
10:21 GMT
256.76k
Below	+0.68%	
Easyjet PLC
EZJ:LSE
550.34
GBX
10:23 GMT
7.59m
Above	+2.26%	
Endeavour Mining plc
EDV:LSE
1,569.00
GBX
10:19 GMT
540.40k
Below	-0.19%	
F&C Investment Trust
FCIT:LSE
1,124.00
GBX
10:22 GMT
324.09k
Below	+0.18%	
Fresnillo PLC
FRES:LSE
635.50
GBX
10:19 GMT
337.53k
Below	+0.08%	
Glencore PLC
GLEN:LSE
376.35
GBX
10:23 GMT
26.03m
Below	+0.12%	
Hikma Pharmaceuticals PLC
HIK:LSE
1,953.40
GBX
10:23 GMT
289.35k
Below	-0.18%	
Hiscox Ltd
HSX:LSE
1,046.00
GBX
10:20 GMT
388.43k
Below	+0.87%	
Howden Joinery Group PLC
HWDN:LSE
823.00
GBX
10:23 GMT
1.44m
Above	+0.67%	
HSBC Holdings PLC
HSBA:LSE
733.30
GBX
10:23 GMT
25.98m
Below	+0.19%	
Imperial Brands PLC
IMB:LSE
2,589.45
GBX
10:20 GMT
1.63m
Below	-1.73%	
International Consolidated Airlines Group SA
IAG:LSE
258.80
GBX
10:23 GMT
22.16m
Below	+1.45%	
J Sainsbury PLC
SBRY:LSE
260.26
GBX
10:23 GMT
4.23m
Below	+2.71%	
JD Sports Fashion PLC
JD.:LSE
104.20
GBX
10:22 GMT
7.67m
Below	+2.51%	
Lloyds Banking Group plc
LLOY:LSE
53.04
GBX
10:23 GMT
100.32m
Below	-0.26%	
M&G PLC
MNG:LSE
199.00
GBX
10:22 GMT
4.35m
Below	+0.58%	
Mondi PLC
MNDI:LSE
1,187.00
GBX
10:23 GMT
633.28k
Below	+0.17%	
NatWest Group PLC
NWG:LSE
397.65
GBX
10:23 GMT
14.02m
Below	+1.31%	
Next PLC
NXT:LSE
9,842.00
GBX
10:22 GMT
136.46k
Below	+0.14%	
Pershing Square Holdings Ord
PSH:LSE
3,707.28
GBX
10:23 GMT
168.03k
Above	+0.36%	
Persimmon PLC
PSN:LSE
1,261.50
GBX
10:22 GMT
1.13m
Below	-0.43%	
Prudential PLC
PRU:LSE
653.00
GBX
10:23 GMT
3.86m
Below	+0.99%	
RELX PLC
REL:LSE
3,723.00
GBX
10:23 GMT
1.96m
Below	+0.11%	
Rentokil Initial PLC
RTO:LSE
400.70
GBX
10:19 GMT
6.38m
Below	+0.58%	
Rio Tinto PLC
RIO:LSE
4,897.50
GBX
10:23 GMT
2.31m
Below	-0.37%	
Scottish Mortgage Investment Trust plc
SMT:LSE
945.34
GBX
10:23 GMT
1.52m
Below	+0.06%	
Shell PLC
SHEL:LSE
2,537.00
GBX
10:22 GMT
7.84m
Below	-0.04%	
Sony Group Corp
SONY:NYQ
19.76
USD
Nov 28 2024
2.49m
Below	+2.01%	
Sony Group Corp
0L83:LSE
19.82
USD
00:00 GMT
9.58k
Above	0.00%	
Standard Chartered PLC
STAN:LSE
984.60
GBX
10:23 GMT
10.91m
Above	+1.15%	
Taylor Wimpey PLC
TW.:LSE
130.45
GBX
10:23 GMT
51.06m
Above	-0.27%	
United Utilities Group PLC
UU.:LSE
1,116.50
GBX
10:21 GMT
1.54m
Above	-1.63%	
Whitbread PLC
WTB:LSE
2,815.00
GBX
10:22 GMT
491.07k
Below	-0.98%	
Zoo Digital Group PLC
ZOO:LSE
34.34
GBX
08:30 GMT
291.41k
Below	-0.46%	
Equity	Last Price	Volume	Today's price
Change - %	Today
Alamtri Resources Indonesia Tbk PT
ADRO:JKT
2,760.00
IDR
09:14 GMT
283.96m
Above	-24.80%	
Bank Rakyat Indonesia (Persero) Tbk PT
BBRI:JKT
4,330.00
IDR
09:13 GMT
266.68m
Below	-1.59%	
BP PLC
BP.:LSE
383.28
GBX
10:23 GMT
45.57m
Above	-0.23%	
Centrica PLC
CNA:LSE
127.48
GBX
10:22 GMT
12.68m
Below	+1.10%	
Compass Group PLC
CPG:LSE
2,702.00
GBX
10:22 GMT
3.60m
Above	-0.15%	
Croda International Plc
CRDA:LSE
3,462.23
GBX
10:22 GMT
277.71k
Below	-0.60%	
Diploma PLC
DPLM:LSE
4,474.00
GBX
10:21 GMT
256.76k
Below	+0.68%	
Easyjet PLC
EZJ:LSE
550.34
GBX
10:23 GMT
7.59m
Above	+2.26%	
Endeavour Mining plc
EDV:LSE
1,569.00
GBX
10:19 GMT
540.40k
Below	-0.19%	
F&C Investment Trust
FCIT:LSE
1,124.00
GBX
10:22 GMT
324.09k
Below	+0.18%	
Fresnillo PLC
FRES:LSE
635.50
GBX
10:19 GMT
337.53k
Below	+0.08%	
Glencore PLC
GLEN:LSE
376.35
GBX
10:23 GMT
26.03m
Below	+0.12%	
Hikma Pharmaceuticals PLC
HIK:LSE
1,953.40
GBX
10:23 GMT
289.35k
Below	-0.18%	
Hiscox Ltd
HSX:LSE
1,046.00
GBX
10:20 GMT
388.43k
Below	+0.87%	
Howden Joinery Group PLC
HWDN:LSE
823.00
GBX
10:23 GMT
1.44m
Above	+0.67%	
HSBC Holdings PLC
HSBA:LSE
733.30
GBX
10:23 GMT
25.98m
Below	+0.19%	
Imperial Brands PLC
IMB:LSE
2,589.45
GBX
10:20 GMT
1.63m
Below	-1.73%	
International Consolidated Airlines Group SA
IAG:LSE
258.80
GBX
10:23 GMT
22.16m
Below	+1.45%	
J Sainsbury PLC
SBRY:LSE
260.26
GBX
10:23 GMT
4.23m
Below	+2.71%	
JD Sports Fashion PLC
JD.:LSE
104.20
GBX
10:22 GMT
7.67m
Below	+2.51%	
Lloyds Banking Group plc
LLOY:LSE
53.04
GBX
10:23 GMT
100.32m
Below	-0.26%	
M&G PLC
MNG:LSE
199.00
GBX
10:22 GMT
4.35m
Below	+0.58%	
Mondi PLC
MNDI:LSE
1,187.00
GBX
10:23 GMT
633.28k
Below	+0.17%	
NatWest Group PLC
NWG:LSE
397.65
GBX
10:23 GMT
14.02m
Below	+1.31%	
Next PLC
NXT:LSE
9,842.00
GBX
10:22 GMT
136.46k
Below	+0.14%	
Pershing Square Holdings Ord
PSH:LSE
3,707.28
GBX
10:23 GMT
168.03k
Above	+0.36%	
Persimmon PLC
PSN:LSE
1,261.50
GBX
10:22 GMT
1.13m
Below	-0.43%	
Prudential PLC
PRU:LSE
653.00
GBX
10:23 GMT
3.86m
Below	+0.99%	
RELX PLC
REL:LSE
3,723.00
GBX
10:23 GMT
1.96m
Below	+0.11%	
Rentokil Initial PLC
RTO:LSE
400.70
GBX
10:19 GMT
6.38m
Below	+0.58%	
Rio Tinto PLC
RIO:LSE
4,897.50
GBX
10:23 GMT
2.31m
Below	-0.37%	
Scottish Mortgage Investment Trust plc
SMT:LSE
945.34
GBX
10:23 GMT
1.52m
Below	+0.06%	
Shell PLC
SHEL:LSE
2,537.00
GBX
10:22 GMT
7.84m
Below	-0.04%	
Sony Group Corp
SONY:NYQ
19.76
USD
Nov 28 2024
2.49m
Below	+2.01%	
Sony Group Corp
0L83:LSE
19.82
USD
00:00 GMT
9.58k
Above	0.00%	
Standard Chartered PLC
STAN:LSE
984.60
GBX
10:23 GMT
10.91m
Above	+1.15%	
Taylor Wimpey PLC
TW.:LSE
130.45
GBX
10:23 GMT
51.06m
Above	-0.27%	
United Utilities Group PLC
UU.:LSE
1,116.50
GBX
10:21 GMT
1.54m
Above	-1.63%	
Whitbread PLC
WTB:LSE
2,815.00
GBX
10:22 GMT
491.07k
Below	-0.98%	
Zoo Digital Group PLC
ZOO:LSE
34.34
GBX
08:30 GMT
291.41k
Below	-0.46%	
Indices
Index	Last Price	Volume	Today's price
Change - %	Today
FTSE 350 Telecommunications Service
FTNMX151020E:FSI
1,966.11
EUR
17:52 GMT
0.00
Exactly	0.00%	
Index	Last Price	Volume	Today's price
Change - %	Today
FTSE 350 Telecommunications Service
FTNMX151020E:FSI
1,966.11
EUR
17:52 GMT
0.00
Exactly	0.00%	
Data delayed at least 20 minutes.
Portfolio news and alerts
REL:LSE
price reached a new 52-week high of 3,749.00 at 03:00 GMT
AlertNov 28 2024
IAG:LSE
price reached a new 52-week high of 257.10 at 03:00 GMT
AlertNov 28 2024
STAN:LSE
price reached a new 52-week high of 976.60 at 03:00 GMT
AlertNov 28 2024
STAN:LSE
Transaction in Own Shares
NewsNov 27 2024
EZJ:LSE
Director/PDMR Shareholding
NewsNov 27 2024
FCIT:LSE
Net Asset Value(s)
NewsNov 27 2024
MNG:LSE
Form 8.3 - DS SMITH PLC
NewsNov 27 2024
STAN:LSE
price reached a new 52-week high of 969.60 at 11:07 GMT
AlertNov 27 2024
LLOY:LSE
Notice of Redemption
NewsNov 27 2024
WTB:LSE
Holding(s) in Company
NewsNov 27 2024
Explore our tools
Growth CalculatorBETA
Explore the time value of money, the impact of regular contributions, and the power of saving over longer timeframes
Alerts
Create detailed alerts and get notified the moment an event happens
Watchlists
Monitor a select list of assets
Portfolio
See how trades would have performed from years past or start from the present
Data archive
Download PDF copies of reports from the newspaper markets data page
World markets
View the performance of global markets and browse news items by region
Equities screener
Find companies based on country, sector, and other equity characteristics
Funds overview
View funds that move the market, screen for funds and read relevant news
Data Provided by LSEG
LSEG
All markets data located on FT.com is subject to the FT Terms & Conditions
All content on FT.com is for your general information and use only and is not intended to address your particular requirements. In particular, the content does not constitute any form of advice, recommendation, representation, endorsement or arrangement by FT and is not intended to be relied upon by users in making (or refraining from making) any specific investment or other decisions.
Any information that you receive via FT.com is at best delayed intraday data and not "real time". Share price information may be rounded up/down and therefore not entirely accurate. FT is not responsible for any use of content by you outside its scope as stated in the FT Terms & Conditions.
Support
View Site Tips
Help Centre
Contact Us
About Us
Accessibility
myFT Tour
Careers
Suppliers
Legal & Privacy
Terms & Conditions
Privacy Policy
Cookie Policy
Manage Cookies
Copyright
Slavery Statement & Policies
Services
Share News Tips Securely
Individual Subscriptions
Professional Subscriptions
Republishing
Executive Job Search
Advertise with the FT
Follow the FT on X
FT Channels
FT Schools
Tools
Portfolio
FT App
FT Digital Edition
FT Edit
Alerts Hub
Business School Rankings
Subscription Manager
News feed
Newsletters
Currency Converter
Community & Events
FT Live Events
FT Forums
Board Director Programme
More from the FT Group
Markets data delayed by at least 15 minutes. © THE FINANCIAL TIMES LTD. FT and ‘Financial Times’ are trademarks of The Financial Times Ltd.
The Financial Times and its journalism are subject to a self-regulation regime under the FT Editorial Code of Practice.

Bank Rakyat Indonesia (Persero) Tbk PTBYRA:BER
Bank Rakyat Indonesia (Persero) Tbk PTBYRA:FRA
Bank Rakyat Indonesia (Persero) Tbk PTBYRA:MUN
Bank Rakyat Indonesia (Persero) Tbk PTBKRKF:PKL
Bank Rakyat Indonesia (Persero) Tbk PTBYRA:STU
Bank Rakyat Indonesia (Persero) Tbk PTBKRKY:PNK
Bank Rakyat Indonesia (Persero) Tbk PTBBRI:DEU
Bank Raya Indonesia Tbk PT0R8:BER
Bank Rakyat Indonesia (Persero) Tbk PTBYR:FRA
Bank Rakyat Indonesia (Persero) Tbk PTBYR:DEU
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
